# Site settings
title: Dimitris Giovanis
email: dgiovan1@jhu.edu
description: Academic webpage of Dimitris Giovanis
baseurl: ""
url: ""

# Google analytics ID: Remove or use your own!
#google_analytics: UA-167467135-1
#google_analytics_4: G-02KDGRRB2T
#google_tag_manager: GTM-TZ9Z7HZ

# Footer info
affiliation: >
    Dimitris Giovanis<br/>
    Assistant Research Professor<br/>
    <a href="https://engineering.jhu.edu/case/" target="_blank">Department of Civil and Systems Engineering</a><br/>
    Johns Hopkins University

location: >
  <a href="https://www.google.com/search?client=safari&rls=en&q=Latrobe+hall+google+maps&ie=UTF-8&oe=UTF-8#" target="_blank">Latrobe Hall</a><br/>
  Johns Hopkins University <br/>
  3400 N. Charles St<br/>
  Baltimore, MD 21218

contact: >
    <a href="mailto:dgiovan1@jhu.edu" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Dimitris via email</a> <br/>
   # <a href="/aboutwebsite.html"><i class="fa fa-github fa-1x"></i> Use this site as a template!</a>

# Pages shown in navbar
nav_pages:
  - name: publications
  - name: talks
  - name: research
  - name: software
  - name: teaching
  - name: Service
   #- name: about


include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

sass:
  sass_dir: _sass
  style: compressed

plugins: ['jekyll/scholar']

scholar:

  last_name: Giovanis
  first_name: [Dimitris]

  style: shb
  locale: en

  source: /cv/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
